plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

# No splitting nested class parts across lines
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# Disable documentation requirement for API project
Style/Documentation:
  Enabled: false

# Frozen string literal comment not needed in Ruby 3.4
Style/FrozenStringLiteralComment:
  Enabled: false

# Allow longer method lengths for API controllers
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/**/*'

# Allow longer blocks in specs and routes
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*'

# Allow longer classes for controllers and models
Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

# Use double quotes consistently
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Use double quotes in interpolation
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Prefer modern hash syntax
Style/HashSyntax:
  EnforcedStyle: ruby19

# Allow both formats for numeric literals
Style/NumericLiterals:
  Enabled: false

# Rails-specific configurations
Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

Rails/Pluck:
  Exclude:
    - 'spec/requests/**/*'

# RSpec-specific configurations
RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

RSpec/LetSetup:
  Enabled: true

# use Shoulda for one-liners
RSpec/ImplicitExpect:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 7

# Performance cops
Performance:
  Enabled: true
